#===-=-=-=-=-=-===-=-=-=-=-=-===#
# nginx + php-fpm
#===-=-=-=-=-=-===-=-=-=-=-=-===#
version: "3.8"
services:
#===-=-=-=-=-=-===-=-=-=-=-=-===# nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - app-network
#===-=-=-=-=-=-===-=-=-=-=-=-===# php
  php:
    image: php:fpm
    container_name: php
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - app-network
#===-=-=-=-=-=-===-=-=-=-=-=-===#  Networks & Volumes
networks:
  app-network:
    driver: bridge
