# Dockerfile for api(Back-end)

# Use Node.js version 14 as the base image
FROM node:14

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the application on port 5000
EXPOSE 5000

# Start the application
CMD ["node", "app.js"]