# Dockerfile for api(Back-end)

# Use Node.js version 14 as the base image
FROM node:14

# Set working directory
WORKDIR /app

# If package.json does not exist, create it and install dependencies;
# Otherwise, copy package.json and package-lock.json if they exist
RUN if [ ! -f package.json ]; then \
        npm init -y; \
    else \
        cp package*.json ./; \
    fi


# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the application on port 5000
EXPOSE 5000

# Start the application
CMD ["node", "app.js"]