#===-=-=-=-=-=-===-=-=-=-=-=-===#
# node(frontend-app) + node(backend-api) + mongo
#===-=-=-=-=-=-===-=-=-=-=-=-===#
version: '3.8'
services:
#===-=-=-=-=-=-===-=-=-=-=-=-===# app
  app:
    build: ./app
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - ./app/src:/usr/src/app-src
    depends_on:
      - api
    networks:
      - base-network
    restart: unless-stopped 
#===-=-=-=-=-=-===-=-=-=-=-=-===# api
  api:
    build: ./api
    container_name: api
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
    volumes:
      - ./api/src:/usr/src/api-src
    depends_on:
      - mongodb
    networks:
      - base-network
    restart: unless-stopped
#===-=-=-=-=-=-===-=-=-=-=-=-===# mongoDB
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - base-network
    restart: unless-stopped
#===-=-=-=-=-=-===-=-=-=-=-=-===#  Networks & Volumes
networks:
  base-network:
