# Dockerfile for app(Front-end)
FROM node:14

# Set working directory
WORKDIR /app

# Copy only package.json and package-lock.json (if exists)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the application on port 3000
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
