#===-=-=-=-=-=-===-=-=-=-=-=-===#
# node(frontend-app) + node(backend-api) + mongo
#===-=-=-=-=-=-===-=-=-=-=-=-===#
version: '3.8'
services:
#===-=-=-=-=-=-===-=-=-=-=-=-===# app
  app:
    build: ./app
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - ./app/src:/app/src
    depends_on:
      - api
    networks:
      - base_network
    restart: unless-stopped 
#===-=-=-=-=-=-===-=-=-=-=-=-===# api
  api:
    build: ./api
    container_name: api
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
    volumes:
      - ./api/src:/app/src
    depends_on:
      - mongo
    networks:
      - base_network
    restart: unless-stopped
#===-=-=-=-=-=-===-=-=-=-=-=-===# mongoDB
  mongoDB:
    image: mongo
    container_name: mongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - base_network
    restart: unless-stopped
#===-=-=-=-=-=-===-=-=-=-=-=-===#  Networks & Volumes
networks:
  base_network:
  
volumes:
  mongo-data:
