#===-=-=-=-=-=-===-=-=-=-=-=-===#
# nginx + php-fpm + phpmyadmin
#===-=-=-=-=-=-===-=-=-=-=-=-===#
version: "3.8"
services:
#===-=-=-=-=-=-===-=-=-=-=-=-===# nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - app-network
#===-=-=-=-=-=-===-=-=-=-=-=-===# php
  php:
    image: php:fpm
    container_name: php
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - app-network
#===-=-=-=-=-=-===-=-=-=-=-=-===# mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: myappdb
     MYSQL_USER: myuser
     MYSQL_PASSWORD: password
    volumes:
     - db:/var/lib/mysql
    networks:
      - app-network
# #===-=-=-=-=-=-===-=-=-=-=-=-===# phpMyAdmin
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
     - mysql
    networks:
      - app-network
#===-=-=-=-=-=-===-=-=-=-=-=-===#  Networks & Volumes
networks:
  app-network:
    driver: bridge

volumes:
  db:
