#===-=-=-=-=-=-===-=-=-=-=-=-===# #===-=-=-=-=-=-===-=-=-=-=-=-===# php-fpm  + nginx + mysql + phpmyadmin 
#===-=-=-=-=-=-===-=-=-=-=-=-===# Version
version: "3.8"
#===-=-=-=-=-=-===-=-=-=-=-=-===# #===-=-=-=-=-=-===-=-=-=-=-=-===# services:
services:
#===-=-=-=-=-=-===-=-=-=-=-=-===# nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./www:/usr/share/nginx/html # in some case /www:/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports: 
      - 80:80
    depends_on:
      - php  # Nginx needs PHP to be ready
    networks:
      - app-network 
#===-=-=-=-=-=-===-=-=-=-=-=-===# php
  php:
    image: php:fpm
    container_name: php
    restart: always      
    volumes:
      - ./www:/var/www/html
    networks:
      - app-network 
#===-=-=-=-=-=-===-=-=-=-=-=-===# mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: myappdb # or localhost
     MYSQL_USER: myuser
     MYSQL_PASSWORD: password
    volumes:  
     - db:/var/lib/mysql
    networks:
      - app-network 
# #===-=-=-=-=-=-===-=-=-=-=-=-===# phpMyAdmin
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
     - mysql # phpMyAdmin needs MySQL to be ready
    networks:
      - app-network 
#===-=-=-=-=-=-===-=-=-=-=-=-===#
#===-=-=-=-=-=-===-=-=-=-=-=-===# #===-=-=-=-=-=-===-=-=-=-=-=-===# Networks & Volumes
networks:
  app-network:
    driver: bridge

volumes:
  db:
